services:
  db_docker:
    restart: always
    container_name: db_docker
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=postgres

